[catalogs]
searchPriorities = []
sortOrders = []

    [[catalogs.globalScopes]]
    catalogIdentifier = 'brew.packages'

        [catalogs.globalScopes.scope]
        kind = 'none'

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.effects'

        [catalogs.globalScopes.scope]
        kind = 'none'

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.emoji'

        [catalogs.globalScopes.scope]
        kind = 'none'

[[comboMode.bindings]]
key = 't'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.applications//Applications/iTerm.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'f'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Library/CoreServices/Finder.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'm'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Messages.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'n'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.applications//Applications/Bear.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'd'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Users/jamievandyke/Downloads' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'h'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Users/jamievandyke' ]
        type = 'savedCommand'

[[comboMode.bindings]]
iconPath = '/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app'
key = 'b'
label = 'Browsers'

    [comboMode.bindings.destination]
    type = 'group'

        [[comboMode.bindings.destination.bindings]]
        key = 'b'
        label = 'Zen'

            [comboMode.bindings.destination.bindings.destination]
            type = 'command'

                [comboMode.bindings.destination.bindings.destination.command]
                actionIdentifier = 'tuna.common-actions/open'
                behavior = 'run'
                presentation = 'automatic'
                subjectIdentifiers = [ 'tuna.applications//Applications/Zen.app' ]
                type = 'savedCommand'

        [[comboMode.bindings.destination.bindings]]
        key = 's'
        label = 'Safari'

            [comboMode.bindings.destination.bindings.destination]
            type = 'command'

                [comboMode.bindings.destination.bindings.destination.command]
                actionIdentifier = 'tuna.common-actions/open'
                behavior = 'run'
                presentation = 'automatic'
                subjectIdentifiers = [ 'tuna.applications//System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app' ]
                type = 'savedCommand'

        [[comboMode.bindings.destination.bindings]]
        key = 'c'
        label = 'Chrome'

            [comboMode.bindings.destination.bindings.destination]
            type = 'command'

                [comboMode.bindings.destination.bindings.destination.command]
                actionIdentifier = 'tuna.common-actions/open'
                behavior = 'run'
                presentation = 'automatic'
                subjectIdentifiers = [ 'tuna.applications//Applications/Google Chrome.app' ]
                type = 'savedCommand'

[[comboMode.bindings]]
key = 'o'
label = 'Orchestrator'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.applications//Applications/Agent Orchestrator.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'l'
label = 'Links'

    [comboMode.bindings.destination]
    type = 'group'

        [[comboMode.bindings.destination.bindings]]
        key = 'a'
        label = 'AWS Console'

            [comboMode.bindings.destination.bindings.destination]
            type = 'url'

                [comboMode.bindings.destination.bindings.destination.url]
                relative = 'https://accounts.google.com/o/saml2/initsso?idpid=C041a81td&spid=432877161643&forceauthn=false'

        [[comboMode.bindings.destination.bindings]]
        key = 'n'
        label = 'New Relic'

            [comboMode.bindings.destination.bindings.destination]
            type = 'url'

                [comboMode.bindings.destination.bindings.destination.url]
                relative = 'https://one.eu.newrelic.com/nr1-core/logger/logs-summary/Mjg5NzIxOHxBUE18QVBQTElDQVRJT058NDIwNjcyMTIz?account=2897218&duration=1800000&state=b6f820ef-14c3-5f8a-c2cd-cb6b66eefdfd'

[hotkeys.app.activate]
carbonKeyCode = 49
carbonModifiers = 256

[hotkeys.app.comboMode]
carbonKeyCode = 38
carbonModifiers = 6912

[hotkeys.app.dictation]
carbonKeyCode = 80
carbonModifiers = 0

[[hotkeys.custom]]
id = '40D93EE3-3DD0-4BDD-B026-19995845BAC8'

    [hotkeys.custom.command]
    actionIdentifier = 'tuna.common-actions/browse'
    behavior = 'run'
    presentation = 'show'
    subjectIdentifiers = [ 'tuna.clipboard/clipboard.history.root' ]
    type = 'savedCommand'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 39
    carbonModifiers = 6912

[settings]
comboModeDoublePressTrigger = 'leftCommand'
comboModeTriggerType = 'doublePress'
dictationActivationMode = 'toggle'
dictationWindowPosition = 'bottomCenter'
resultListNavigationBindings = 'vimStyle'
screenPreference = 'primary'
shortcutDisplayUsesHyperSymbol = false
spacebarBehavior = 'switchToTextMode'

[[smartLinks.entries]]
enabled = true
name = 'AWS Console'
requiresInput = true
template = 'https://accounts.google.com/o/saml2/initsso?idpid=C041a81td&spid=432877161643&forceauthn=false'

[[smartLinks.entries]]
enabled = true
name = 'Amazon'
requiresInput = true
template = 'https://www.amazon.co.uk/s?k={{input}}&s=review-rank'

[[smartLinks.entries]]
enabled = true
name = 'GitHub'
requiresInput = true
template = 'https://github.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'Kagi'
requiresInput = true
template = 'https://www.kagi.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'YouTube'
requiresInput = true
template = 'https://www.youtube.com/results?search_query={{input}}'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.plugins.mymind'

    [catalogSettings.values]
    AccessLevel = 'full-access'
    KeyID = 'ey986l1gRv6hGGJyMyamkW'

[[catalogSettings]]
catalogIdentifier = 'tuna.prompts'

    [catalogSettings.values]
    Provider = 'apple'
