[[snippets]]
trigger = ":date"
replace = "{{date}}"
description = "Current date"

[[snippets]]
trigger = ":time"
replace = "{{time}}"
description = "Current time"

[[snippets]]
trigger = ":clip"
replace = "{{clipboard}}"
description = "Paste current clipboard text"

[[snippets]]
trigger = ":sig"
replace = "Cheers,\nJamie{{cursor}}"
description = "Signature snippet with cursor placement"

[[snippets]]
trigger = ":bi"
replace = "op run --env-file=.env.development.local -- bundle install"
description = "Run bundle install with 1Password cli"

[[snippets]]
trigger = ":be"
replace = "op run --no-masking --env-file=.env.development.local -- bundle exec "
description = "Run bundle exec with 1Password cli"

[[snippets]]
trigger = ":op"
replace = "op run --no-masking --env-file=.env.development.local -- "
description = "Run with 1Password cli"

[[snippets]]
trigger = ":def"
replace = "def {{prompt:Method name}}\n  echo \"{{prompt:Echo what\"}}\nend"
description = "Create an echo method"
